### ISSUE TITLE
在空目录下，初始化项目报错

### ISSUE THREAD

**Issue by EchoVie** [tzsk/vite-pretty-lint#15]
![image](https://user-images.githubusercontent.com/57256068/176110839-8db124db-85e5-4c85-a6df-97e37d4b4e6f.png)

no such file or directory, open '/Users/eleme/Desktop/project/vite.config.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at run (file:///Users/eleme/.npm/_npx/455c2e6b658650a8/node_modules/create-vite-pretty-lint/lib/main.js:62:36) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/eleme/Desktop/project/vite.config.js'

**Comment by tzsk** [comment]
Hey thanks for reporting the issue.

Can you please tell me what type of vite project you have? React-TS or React or Vue-TS or Vue?

And can you please ensure that you have vite.config.js?

Or maybe vite.config.ts?

**Comment by tzsk** [comment]
Most importantly is the project created using vite?

**Comment by wencaizhang** [comment]
@EchoVie 

你需要在一个由 vite 创建的项目中使用 vite-pretty-lint

**Comment by tzsk** [comment]
Closing: Unrelated thanks @wencaizhang
